### PR TITLE
Fix high contrast theme bugs

### LINKED ISSUE #286: High contrast theme bugs
### Describe the bug

There are a handful of component theming bugs when the VS Code high contrast theme is applied.

### To reproduce

- Install and run the `all-components` sample extension
- Set the VS Code theme to High Contrast
- View the various visual states of buttons, dropdowns, and data grids

### Expected behavior

Buttons, dropdowns, and data grids should adhere to/match the visual states of native VS Code buttons, dropdowns, and data grids.

### Screenshots

Incorrect button backgrounds:

Screen Shot 2021-11-01 at 5 24 52 PM

Correct button backgrounds:

Screen Shot 2021-11-01 at 5 24 48 PM

Incorrect icon button default state:

Screen Shot 2021-11-02 at 2 47 08 PM

Correct icon button default state:

Screen Shot 2021-11-02 at 2 47 22 PM

Incorrect icon button hover state:

Screen Shot 2021-11-02 at 2 47 16 PM

Correct icon button hover state:

Screen Shot 2021-11-02 at 2 47 39 PM

Incorrect dropdown option selected state:

Screen Shot 2021-11-02 at 2 46 18 PM

Correct dropdown option selected state:

Screen Shot 2021-11-02 at 2 46 35 PM

Incorrect data grid selected/hover state:

Screen Shot 2021-11-02 at 2 45 48 PM

Correct data grid selected/hover state:

Screen Shot 2021-11-02 at 2 46 01 PM

### Desktop (please complete the following information):

-   OS Version: _macOS 11.6_
-   Toolkit Version: _v0.8.3_

### PR DESCRIPTION
**Pull request by hawkticehurst**
### Link to relevant issue

This pull request resolves #286

### Description of changes

Fixes a variety of component theming bugs when VS Code uses a high contrast theme. A list of the various bugs can be found in the issue linked above.

### CODE REVIEW

File: src/design-tokens.ts [hunk 1]
```diff
@@ -3,10 +3,28 @@
...
 
+/**
+ * Developer note:
+ *
+ * There are some tokens defined in this file that make use of `--fake-vscode-token`. This is
+ * done when a toolkit token should be added to the tokenMappings map (and subsequently altered
+ * in the applyTheme function) but does not have a corresponding VS Code token that can be used.
+ *
+ * An example is buttonIconHoverBackground token which does not have a corresponding VS Code token
+ * at this time (it's a hardcoded value in VS Code), but needs to be adjusted to be transparent when a
```
Comment (daviddossett) [inline src/design-tokens.ts:14]: Should this be an issue filed on /vscode? If it's a simple enough change I can add it to my list

**Review by daviddossett — APPROVED** [review]
Looks good!

File: src/design-tokens.ts (hunk 1 above)
Comment (hawkticehurst) [reply src/design-tokens.ts:14]: I wouldn't be against that! Would certainly simplify the toolkit theming code

Comment (hawkticehurst) [reply src/design-tokens.ts:14]: The big request is that this token should either be set to transparent or null (not exist) in high contrast themes

Comment (hawkticehurst) [reply src/design-tokens.ts:14]: Otherwise, its value seems to be `rgba(90, 93, 94, 0.31)` across all themes?

Comment (hawkticehurst) [reply src/design-tokens.ts:14]: As I think about it, this could actually be a really nice opportunity to customize things a bit because I think this value ends up resulting in a less than ideal contrast ratio in light themes

Comment (hawkticehurst) [reply src/design-tokens.ts:14]: Screen Shot 2022-02-03 at 2 50 17 PM
